"""added equation to Graph

Revision ID: 899ad5dc2d51
Revises: eee1ef7bb354
Create Date: 2023-05-04 11:11:47.003090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '899ad5dc2d51'
down_revision = 'eee1ef7bb354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graphs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equation', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graphs', schema=None) as batch_op:
        batch_op.drop_column('equation')

    # ### end Alembic commands ###
