"""Create tables

Revision ID: eee1ef7bb354
Revises: 
Create Date: 2023-05-01 16:43:30.544439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee1ef7bb354'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graphs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('x_1', sa.Integer(), nullable=True),
    sa.Column('y_1', sa.Integer(), nullable=True),
    sa.Column('x_2', sa.Integer(), nullable=True),
    sa.Column('y_2', sa.Integer(), nullable=True),
    sa.Column('x_3', sa.Integer(), nullable=True),
    sa.Column('y_3', sa.Integer(), nullable=True),
    sa.Column('x_4', sa.Integer(), nullable=True),
    sa.Column('y_4', sa.Integer(), nullable=True),
    sa.Column('x_5', sa.Integer(), nullable=True),
    sa.Column('y_5', sa.Integer(), nullable=True),
    sa.Column('hw_name', sa.String(), nullable=True),
    sa.Column('problem_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graphs'))
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('instructor_name', sa.String(), nullable=True),
    sa.Column('instructor_email', sa.String(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students')),
    sa.UniqueConstraint('username', name=op.f('uq_students_username'))
    )
    op.create_table('student_graphs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('graph_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['graph_id'], ['graphs.id'], name=op.f('fk_student_graphs_graph_id_graphs')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_student_graphs_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_graphs'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_graphs')
    op.drop_table('students')
    op.drop_table('graphs')
    # ### end Alembic commands ###
